create table user(
  id INT AUTO_INCREMENT PRIMARY KEY,
  IP VARCHAR(255) NOT NULL,
  Naviguator VARCHAR(255) NOT NULL,
  GPS VARCHAR(255) NOT NULL,
  OS VARCHAR(255) NOT NULL,
  UUID VARCHAR(255) NOT NULL,
  Date DATETIME NOT NULL,
);


create table redirect(
  id INT AUTO_INCREMENT PRIMARY KEY,
  FROM_URL VARCHAR(255) NOT NULL,
  TO_URL VARCHAR(255) NOT NULL,
  ENDTIME TIMESTAMP NOT NULL,
  UUID VARCHAR(255) NOT NULL,
  TIME INT DEFAULT 1000,
  GPS BOOL DEFAULT FALSE,
);
